### ISSUE TITLE
Redirect after form submission

### ISSUE THREAD

**Issue by Crispin-Courtenay** [Crispin-Courtenay/SWFLB-Website#19]
https://www.sharkaroo.io/shark-a-who

Others are just as guilty. Cannot strand user on Landing Page.

**Comment by ricp** [comment]
I dont understand what you want ? after form submission this message is displayed to the user:

"Thanks for submitting the form. Please allow for several days while we prepare your information. "

You want to redirect him somewhere instead ?

**Comment by Crispin-Courtenay** [comment]
Perhaps offer up some solutions options...keep user engaged, and "aha moment"

**Comment by Crispin-Courtenay** [comment]
Closing - but I think there is a more elegant solution in the future. 

Worth noting that I have made most (all?) forms on landing pages with no navigation. the only way forward is to complete the form, the only way back is via the logo.
