### ISSUE TITLE
DNS Bugs

### ISSUE THREAD

**Issue by Crispin-Courtenay** [Crispin-Courtenay/SWFLB-Website#26]
- The server at sharkaroo.io sent a HTTP redirect. Your web address has been updated. Please try again.
- The server at www.sharkaroo.io sent a HTTP redirect. Your web address has been updated. Please try again.
- Could not read sharkaroo.io/robots.txt. .

This may be my fault - I added do not follow - it was supposed to be page specific.

**Comment by Crispin-Courtenay** [comment]
Removing all do-not-follow to see if this resolves.

**Comment by Crispin-Courtenay** [comment]
Did not fix anything. :(

**Comment by Crispin-Courtenay** [comment]
This was all working less than a few hours ago - anything change on the DNS End?

**Comment by Crispin-Courtenay** [comment]
Not resolving w/o www. (did not notice this) .
![image](https://user-images.githubusercontent.com/16553400/45530560-251b5a00-b7a0-11e8-98f4-886654ba311a.png)

Shit!

**Comment by Crispin-Courtenay** [comment]
Support in France?

Try again?

Move to Route 53 (where everything always works). 

**All you need to do to move to Route 53 is change name servers - AWS does the rest.

**Comment by Crispin-Courtenay** [comment]
Let Hieu unbork it?

He is really good at this. 

![image](https://user-images.githubusercontent.com/16553400/45530637-9a872a80-b7a0-11e8-88dd-44e0a9c32cc7.png)

**Comment by Crispin-Courtenay** [comment]
Removed all do not follows - nothing. 

This is DNS level. A certain level of hell that is only (slightly) worse by SSL and then configuring an email server.

**Comment by ricp** [comment]
Checked the DNS and everything looks fine, the www are redirected correctly to the Hubspot address, the root domains are permanently redirected to https://www.sharkaroo.io

Don't see any problem here. Tested the root redirects (sharkaroo.io, sharkaroo.fr, sharkaroo.*) and everything works fine
